oneup_flysystem:
  adapters:
    public_uploads_adapter:
        local:
          directory: '%kernel.project_dir%/public/%uploads_dir_name%'

    private_uploads_adapter:
        local:
          directory: '%kernel.project_dir%/%uploads_dir_name%'

  filesystems:

    public_uploads_filesystem:
      adapter: public_uploads_adapter

    private_uploads_filesystem:
      adapter: private_uploads_adapter

